[package]
name = "markov"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bincode = "2.0.1"
csv = "1.4.0"
ndarray = "0.17.1"
ndarray-rand = "0.16.0"
rand = "0.9.2"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
